# Generated by Django 4.2.6 on 2023-10-23 02:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('type', models.IntegerField(verbose_name='Тип продукта')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail клиента')),
                ('link', models.CharField(max_length=50, verbose_name='Инста клиента')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('paid', models.DateTimeField(default=None, verbose_name='Оплачен')),
                ('client_ip', models.CharField(max_length=40, verbose_name='IP Клиента')),
                ('status', models.IntegerField(default=0, verbose_name='Статус заказа')),
                ('approve_order', models.IntegerField(default=0, verbose_name='Какая то непонятная хуйня из стока')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(verbose_name='Тип продукта')),
                ('count_field', models.CharField(max_length=40, verbose_name='Количество')),
                ('new_price', models.IntegerField(verbose_name='Новая цена')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
