# Generated by Django 4.2.6 on 2023-10-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.CharField(default=None, max_length=50, verbose_name='Инста клиента'),
        ),
    ]
