# Generated by Django 4.2.6 on 2023-10-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(null=True, verbose_name='Оплачен'),
        ),
    ]
