# Generated by Django 4.2.6 on 2023-10-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link',
            field=models.CharField(max_length=50, verbose_name='Инста клиента'),
        ),
    ]
