INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (1, 1, '250', 3, 63);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (2, 1, '500', 5, 67);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (3, 1, '1 000', 9, 69);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (4, 1, '2 500', 15, 62);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (5, 1, '5 000', 25, 68);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (6, 1, '10 000', 49, 65);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (7, 1, '25 000', 99, 70);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (8, 1, '50 000', 159, 71);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (9, 5, '250', 2, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (10, 5, '500', 3, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (11, 5, '1 500', 5, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (12, 5, '5 000', 15, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (13, 6, '250', 4, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (14, 6, '500', 7, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (15, 6, '1 000', 12, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (16, 6, '2 500', 19, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (17, 6, '5 000', 29, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (18, 6, '10 000', 49, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (19, 6, '25 000', 99, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (20, 6, '50 000', 159, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (21, 7, '1 000', 1, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (22, 7, '5 000', 3, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (23, 7, '10 000', 5, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (24, 7, '25 000', 13, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (25, 7, '50 000', 25, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (26, 7, '100 000', 49, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (27, 7, '500 000', 99, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (28, 7, '1 000000', 159, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (29, 2, '100', 1, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (30, 2, '250', 2, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (31, 2, '500', 4, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (32, 2, '1 000', 7, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (33, 2, '2 500', 12, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (34, 2, '5 000', 15, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (35, 2, '10 000', 19, 1);
INSERT INTO main_products (id, type, count_field, new_price, discount) VALUES (36, 2, '25 000', 25, 1);
